define [], () ->

  TASK_TYPE =
    SEND_TASK: 1
    RECEIVE_TASK: 2

  TASK_STATUS =
    NEW: 0
    STARTED: 1
    STOPPED: 2
    COMPLETED: 3
    RETRY: 4
    BROKEN: 5

  MAX_SEND_WORKERS = 4
  MAX_RECEIVE_WORKERS = 4

  WORKER_STATUS =
    WAITING: 1
    BUSY: 2
    NEED_RESTART: 3

  constants =
    MAX_SEND_WORKERS: MAX_SEND_WORKERS
    MAX_RECEIVE_WORKERS: MAX_RECEIVE_WORKERS
    WORKER_STATUS: WORKER_STATUS
    CHUNK_SIZE: 1024 * 512 # 0,5 MB
    TASK_TYPE: TASK_TYPE
    TASK_STATUS: TASK_STATUS


  return constants